# https://github.com/SeleniumHQ/docker-selenium
version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    volumes:
      - ./application:/code
    ports:
      - "8000:8000"
      # デバッグ用ポート
      - "8080:8080"
    environment:
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
    tty: true
    networks:
      selenium-hub:

  chrome:
    image: selenium/node-chrome:4.9.1-20230508
    container_name: selenium-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      selenium-hub:

  edge:
    image: selenium/node-edge:4.9.1-20230508
    container_name: selenium-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      selenium-hub:

  firefox:
    image: selenium/node-firefox:4.9.1-20230508
    container_name: selenium-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      selenium-hub:

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      selenium-hub:


networks:
  selenium-hub: